# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets: # Contient la liste des filtres
        carroussel: # Nom du filtre
            quality: 75 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                thumbnail: # Filtre "Thumbnail"
                    size: [843, 697] # Taille de l'image de sortie
                    mode: outbound # Découpage de l'image
        
        coverImage: # Nom du filtre
            quality: 75 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                thumbnail: # Filtre "Thumbnail"
                    size: [550, 658] # Taille de l'image de sortie
                    mode: outbound # Découpage de l'imaget

        postImage: # Nom du filtre
            quality: 75 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                thumbnail: # Filtre "Thumbnail"
                    size: [1170, 600] # Taille de l'image de sortie
                    mode: outbound # Découpage de l'imaget


        categoryImage: # Nom du filtre
            quality: 75 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                thumbnail: # Filtre "Thumbnail"
                    size: [530, 568] # Taille de l'image de sortie
                    mode: outbound # Découpage de l'imaget


        aboutImage: # Nom du filtre
            quality: 75 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                thumbnail: # Filtre "Thumbnail"
                    size: [652, 448] # Taille de l'image de sortie
                    mode: outbound # Découpage de l'imaget
