# Le nom de l'application
name: app

# Le type d'application à construire
type: php:7.4
build:
    flavor: composer

variables:
    env:
        # Configuration des variables d'environnement pour Symfony
        APP_ENV: 'dev'
        APP_DEBUG: 1

# Actions à exécuter à la construction et au déploiement
hooks:
    build: |
        set -e
        php bin/console assets:install --no-debug
        php bin/console cache:clear
    deploy: |
        php bin/console assets:install --symlink --relative public
        php bin/console cache:clear
        php bin/console make:migration
        php bin/console doctrine:migrations:migrate

# Les services utilisés
relationships:
    database: 'db:mysql'

# L'espace disque configurés
disk: 2048

# Les dossiers qui doivent rester accessibles en écriture
mounts:
    "/var/cache": "shared:files/cache"
    "/var/log": "shared:files/log"
    "/var/sessions": "shared:files/sessions"

# La configuration web
web:
    locations:
        "/":
            # Dossier public
            root: "public"
            # Le contrôleur frontal (qui doit recevoir toutes les requêtes)
            passthru: "/index.php"

dependencies:
      php:
          composer/composer: "^2"

